export const WEAPONS = {
    // Western Melee Weapons
    SPEAR: {
      id: 'spear',
      name: 'Spear',
      faction: 'west',
      stance: 'single',
      targetType: 'single',
      damageType: 'piercing',
      vfxType: 'thrust',
      range: 150,
      baseDamage: 25,
      attackSpeed: 3.0, // attacks per second
      specialAbility: 'lunge',
      icon: 'spear.png',
    },
    BATTLE_AXE: {
      id: 'battleaxe',
      name: 'Battle Axe',
      faction: 'west',
      stance: 'single',
      targetType: 'multi',
      damageType: 'slashing',
      vfxType: 'slash',
      range: 100,
      baseDamage: 30,
      attackSpeed: 1.0,
      specialAbility: 'spin',
      icon: 'axe.png',
    },
    GREAT_AXE: {
      id: 'greataxe',
      name: 'Great Axe',
      faction: 'west',
      stance: 'double',
      targetType: 'multi',
      damageType: 'slashing',
      vfxType: 'slash',
      range: 100,
      baseDamage: 45,
      attackSpeed: 0.7,
      specialAbility: 'whirlwind',
      icon: 'waraxe.png',
    },
    GREAT_HAMMER: {
      id: 'greathammer',
      name: 'Great Hammer',
      faction: 'west',
      stance: 'double',
      targetType: 'single',
      damageType: 'blunt',
      vfxType: 'blunt',
      range: 80,
      baseDamage: 50,
      attackSpeed: 0.6,
      specialAbility: 'smash',
      icon: 'hammer.png',
    },

    // Eastern Melee Weapons
    BO: {
      id: 'bo',
      name: 'Bo',
      faction: 'east',
      stance: 'double',
      targetType: 'single',
      damageType: 'blunt',
      vfxType: 'blunt',
      range: 120,
      baseDamage: 20,
      attackSpeed: 1.5,
      specialAbility: 'charged_smack',
      icon: 'mace.png',
    },
    FIST: {
      id: 'fist',
      name: 'Fist',
      faction: 'east',
      stance: 'single',
      targetType: 'single',
      damageType: 'blunt',
      vfxType: 'blunt',
      range: 50,
      baseDamage: 15,
      attackSpeed: 4.0,
      specialAbility: 'grab_throw',
    },
  };
